### ISSUE TITLE
Thread-safety problem with NEI Blood Magic add-on

### ISSUE THREAD

**Issue by planetguy32** [fnuecke/CraftingCosts#5]
There seems to be a compatibility problem with NEI's Blood Magic add-on - most complex recipes show their costs as "java.util.ConcurrentModificationException". Stack trace:

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
    at java.util.ArrayList$Itr.next(ArrayList.java:831)
    at joshie.alchemicalWizardy.nei.NEIBloodOrbShapedHandler$CachedBloodOrbRecipe.setIngredients(NEIBloodOrbShapedHandler.java:41)
    at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:35)
    at joshie.alchemicalWizardy.nei.NEIBloodOrbShapedHandler$CachedBloodOrbRecipe.<init>(NEIBloodOrbShapedHandler.java:24)
    at joshie.alchemicalWizardy.nei.NEIBloodOrbShapedHandler.forgeShapedRecipe(NEIBloodOrbShapedHandler.java:124)
    at joshie.alchemicalWizardy.nei.NEIBloodOrbShapedHandler.loadCraftingRecipes(NEIBloodOrbShapedHandler.java:78)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
    at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:107)
    at joshie.alchemicalWizardy.nei.NEIBloodOrbShapedHandler.loadCraftingRecipes(NEIBloodOrbShapedHandler.java:70)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
    at li.cil.cc.ClientProxy$$anonfun$4.apply(ClientProxy.scala:177)
    at li.cil.cc.ClientProxy$$anonfun$4.apply(ClientProxy.scala:177)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at li.cil.cc.ClientProxy.li$cil$cc$ClientProxy$$computeCosts(ClientProxy.scala:177)
    at li.cil.cc.ClientProxy$$anonfun$21.apply(ClientProxy.scala:243)
    at li.cil.cc.ClientProxy$$anonfun$21.apply(ClientProxy.scala:243)
    at li.cil.cc.ClientProxy$$anonfun$1.liftedTree1$1(ClientProxy.scala:131)
    at li.cil.cc.ClientProxy$$anonfun$1.apply(ClientProxy.scala:131)
    at li.cil.cc.ClientProxy$$anonfun$1.apply(ClientProxy.scala:127)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by fnuecke** [comment]
Thanks! That's too bad, guess I'll have to do the recipe fetching in the client thread after all. Will do ~~later today~~.
